---
- name: Add Routes to all VMs
  hosts: all
  become: yes
  tasks:

    - name: Add default route for HostA
      when: inventory_hostname == 'HostA'
      shell: sudo ip route add default via 10.0.10.1

    - name: Add default route for HostB
      when: inventory_hostname == 'HostB'
      shell: sudo ip route add default via 10.0.30.1

    - name: Add routes for R1
      when: inventory_hostname == 'R1'
      shell: sudo ip route add 10.0.30.0/24 via 10.0.20.2 dev eth2

    - name: Add routes for R2
      when: inventory_hostname == 'R2'
      shell: sudo ip route add 10.0.10.0/24 via 10.0.20.1 dev eth1

